env_type: dev

storage:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  dbname: auth

server:
  host: localhost
  port: 8080
  timeout: 1h

jwt:
  token_ttl: 12h

debug: true